-- BAI 1
--1 
DECLARE @luongTBPhong TABLE (MaPB int, LuongTB float)
INSERT INTO @luongTBPhong 
SELECT PHG, AVG(LUONG) FROM NHANVIEN GROUP BY PHG

SELECT TENNV, PHG, LUONG, LuongTB,
TrangThai = CASE
WHEN LUONG > LuongTB THEN 'KO TANG LUONG'  ELSE 'TANG LUON' END 
FROM NHANVIEN A
	JOIN @luongTBPhong B ON A.PHG = B.MaPB

-- 2
DECLARE @luongTBPhong2 TABLE (MaPB int, LuongTB float)
INSERT INTO @luongTBPhong2 
SELECT PHG, AVG(LUONG) FROM NHANVIEN GROUP BY PHG

SELECT TENNV, PHG, LUONG, LuongTB, TrangThai = CASE
WHEN LUONG > LuongTB THEN 'Truong phong'  ELSE 'nhan vien' END 
FROM NHANVIEN A
	JOIN @luongTBPhong2 B ON A.PHG = B.MaPB

-- 3
SELECT TENNV = CASE 
WHEN PHAI = 'Nam' THEN 'Mr. ' + TENNV
WHEN PHAI = N'Nữ' THEN 'Ms. ' + TENNV
ELSE 'NULL ' + TENNV
END 
FROM NHANVIEN

-- 3
SELECT TENNV, LUONG, 
 thue = CASE
	WHEN LUONG BETWEEN 0 AND 25000 THEN LUONG*0.1
	WHEN LUONG BETWEEN 25000 AND 30000 THEN LUONG*0.12
	WHEN LUONG BETWEEN 30000 AND 40000 THEN LUONG*0.15
	WHEN LUONG BETWEEN 40000 AND 50000 THEN LUONG*0.2
	ELSE LUONG*0.25
	END
FROM NHANVIEN

-- BAI 2
-- 1
DECLARE @i int = 2, @dem int
set @dem = (SELECT COUNT(*) FROM NHANVIEN)
WHILE (@i < @dem)
BEGIN 
	SELECT MANV, HONV, TENLOT, TENNV FROM NHANVIEN
	WHERE CAST(MANV AS INT) = @i
	SET @i += 2
END

-- 2
DECLARE @i int = 2, @dem int
set @dem = (SELECT COUNT(*) FROM NHANVIEN)

WHILE (@i < @dem)
BEGIN 
	IF(@i = 4)
		BEGIN
			SET @i += 2
			CONTINUE 
		END
	SELECT MANV, HONV, TENLOT, TENNV FROM NHANVIEN
	WHERE CAST(MANV AS INT) = @i
	SET @i += 2
END

-- BAI 3
-- 1
BEGIN TRY 
	INSERT PHONGBAN
	VALUES ('Ke Hoach',7,'0',GETDATE())
	PRINT 'CHEN THANH CONG'
END TRY
BEGIN CATCH
	PRINT 'LOI ' + CONVERT(VARCHAR, ERROR_NUMBER()) + ' => ' +ERROR_MESSAGE()
END CATCH

-- 2
BEGIN TRY
	declare @a int = 1, @b int = 0, @ketQua int
	set @ketQua = @a/@b
end try
begin catch
	declare @ErMs varchar(500), 
			@ErSe int,
			@ErSt int
	select @ErMs = ERROR_MESSAGE(),
			@ErSe = ERROR_SEVERITY(),
			@ErSt = ERROR_STATE()
	raiserror (@ErMs, @ErSe, @ErSt)
end catch